name: Generate iCal File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: cd icalgenerator && yarn install

    - name: Generate iCal file
      run: node icalgenerator/generate-ical.js

    - name: Commit and push iCal file
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git pull origin ${GITHUB_REF}
        git add website/public/calendar.ics
        git commit -m "Generate iCal file"
        git push origin HEAD:${GITHUB_REF}

